# permissions for end users to view cowboys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cowboy-viewer-role
rules:
- apiGroups:
  - demo.ai.cast
  resources:
  - cowboys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.ai.cast
  resources:
  - cowboys/status
  verbs:
  - get
